### ISSUE TITLE
이메일을 통한 아이디/비밀번호 찾기

### ISSUE THREAD

**Issue by jaehyuk7** [AllForOneTeam/allForOneReview#26]
### TODO
- [x] 이메일 인증 기능

- [x] 아이디 찾기 기능

- [x] 비밀번호 재설정 기능

### 작업내역
- 이메일 보내기 기능 완료.
- 이메일로 무작위 코드 전송 성공.
- 보낸 코드를 통해 인증 성공 후 아이디 사용 가능하게 활성화 완료.
- 이메일 인증 추가하니 오류가 발생한 로그인 기능 버그 픽스.
- 아이디 찾기 기능 추가 완료.
- 비밀번호 재설정 기능 추가 완료.
- 체크박스 체크해야 회원가입 완료가 가능한 기능 추가 완료.

### 상세내용
- 회원가입 때, 이메일 인증 기능을 추가 했는데 무슨 오류인지 모를 오류로 인해 메시지가 보내지지 않았습니다.
- 시간 설정 잘못해서 인증 이메일 유효 시간이 너무 짧게 설정되었던 오류 수정.
- 로깅 기능을 추가하는 것이 디버깅에 도움을 준다는 것을 알게 되어 일단 추가는 해봤으나 제대로 활용할 능력이 부족해 활용은 잘하지 못했습니다.
- 매개변수 이름 정보를 정확히 지정하지 않아 제대로 기능하지 않는 실수를 여러 번 반복하여 익숙해졌습니다.
- 서로가 서로를 의존하는 관계로 코드를 잘못 짜면 아예 시동이 되지 않는다는 것을 의도치 않게 확인했습니다.
