### ISSUE TITLE
html, css 병합

### ISSUE THREAD

**Issue by jaehyuk7** [AllForOneTeam/allForOneReview#4]
### TODO

- [x] html, css, img 파일 가져오기

- [x] 타임리프 설정하기

- [x] 이미지 및 링크 경로 바꾸기

- [x] 해당 html를 각 controller에 연결

### 작업내역
- VScode에서 작업한 html, css 파일 인텔리제이로 가져와서 연결하기
