### ISSUE TITLE
회원가입 관련된 부분들 기능개선 및 버그 픽스

### ISSUE THREAD

**Issue by jaehyuk7** [AllForOneTeam/allForOneReview#45]
### TODO
- [x] 회원가입 버튼을 여러 번 누르면 추가로 회원가입 시도하는 것으로 감지하는 것 고치기
- [x] 미인증 상태 로그인 시도 시, 이메일 인증으로 이동하기
- [x] 이메일에 인증 url 추가

### 작업내역
- 회원가입 시, 회원가입 확인 팝업 추가.
- 회원가입 버튼 누른 후 버튼 로딩 표시 추가하여 추가 클릭 불가능하게 완료.
- 이메일에 인증하기 버튼 추가 및 버튼 클릭 시 자동 인증 후 로그인 화면으로 이동하는 기능 추가.

### 상세내용
- 회원가입이 눌렸는지 모르고 여러번 누를 시 같은 정보로 회원가입을 2번 시도한 것으로 인식하는 것 때문에 회원가입 버튼을 한 번만 누를 수 있도록 수정. 눌렸다는 것을 알리기 위해 팝업과 버튼의 로딩 액션을 하는 자바스크립트를 추가.
- 실수로 인증을 완료하지 못했을 사용자를 위해 미인증 아이디로 로그인 시도 시, 인증 코드 재발급 및 재발송 기능 추가.
- 이메일에 인증화면으로 이동하는 url만 추가하려고 했다가 자동으로 인증을 하는 기능 추가. 추후 문제가 없다면 이메일 발급 코드를 수동으로 입력하는 기능 자체를 없앨 가능성이 있습니다.
